version: '3.8'
services:
  postgres-ms2:
    image: postgres:16
    container_name: postgres-ms2
    environment:
      POSTGRES_PASSWORD: smokecast123
      POSTGRES_DB: urban_exposure
    ports:
      - "5432:5432"
    volumes:
      - pg_ms2_data:/var/lib/postgresql/data
volumes:
  pg_ms2_data: