const publicBasePath = (process.env.PUBLIC_BASE_PATH || '/').trim().replace(/\/+$/, '') || '/';

const spec = {
  openapi: '3.0.3', info: {title: 'MS2 — Urban Exposure API', version: '1.0.0', description: 'Catálogo de ciudades y localidades expuestas.'},
  servers: [{url: publicBasePath}],
  paths: {
    '/health': {get: {tags: ['Monitoreo'], summary: 'Estado de PostgreSQL', responses: {'200': {description: 'Servicio disponible'}, '503': {description: 'Base no disponible'}}}},
    '/api/v1/cities': {get: {tags: ['Ciudades'], summary: 'Lista ciudades', parameters: [{name: 'page', in: 'query', schema: {type: 'integer', minimum: 0, default: 0}}, {name: 'size', in: 'query', schema: {type: 'integer', minimum: 1, maximum: 500, default: 100}}], responses: {'200': {description: 'Ciudades'}}}, post: {tags: ['Ciudades'], summary: 'Crea una ciudad', requestBody: {required: true, content: {'application/json': {schema: {$ref: '#/components/schemas/CityInput'}}}}, responses: {'201': {description: 'Creada'}, '400': {description: 'Datos inválidos'}}}},
    '/api/v1/cities/bulk': {post: {tags: ['Ciudades'], summary: 'Inserta ciudades en bulk', requestBody: {required: true, content: {'application/json': {schema: {$ref: '#/components/schemas/CityBulkInput'}}}}, responses: {'201': {description: 'Ciudades insertadas'}, '400': {description: 'Bulk inválido'}}}},
    '/api/v1/cities/near': {get: {tags: ['Ciudades'], summary: 'Busca ciudades cercanas', parameters: [{name: 'lat', in: 'query', required: true, schema: {type: 'number', minimum: -90, maximum: 90}}, {name: 'lon', in: 'query', required: true, schema: {type: 'number', minimum: -180, maximum: 180}}, {name: 'radius_km', in: 'query', schema: {type: 'number', minimum: 0, maximum: 20040, default: 150}}], responses: {'200': {description: 'Ciudades ordenadas por distancia'}}}},
    '/api/v1/sensitive-sites': {get: {tags: ['Sitios sensibles'], summary: 'Lista sitios sensibles', parameters: [{name: 'city_id', in: 'query', schema: {type: 'integer', minimum: 1}}, {name: 'page', in: 'query', schema: {type: 'integer', minimum: 0, default: 0}}, {name: 'size', in: 'query', schema: {type: 'integer', minimum: 1, maximum: 500, default: 100}}], responses: {'200': {description: 'Sitios sensibles'}}}, post: {tags: ['Sitios sensibles'], summary: 'Crea un sitio sensible', requestBody: {required: true, content: {'application/json': {schema: {$ref: '#/components/schemas/SensitiveSiteInput'}}}}, responses: {'201': {description: 'Creado'}}}},
    '/api/v1/sensitive-sites/bulk': {post: {tags: ['Sitios sensibles'], summary: 'Inserta sitios sensibles en bulk', requestBody: {required: true, content: {'application/json': {schema: {$ref: '#/components/schemas/SensitiveSiteBulkInput'}}}}, responses: {'201': {description: 'Sitios insertados'}, '400': {description: 'Bulk inválido'}}}},
    '/api/v1/cities/{id}/sensitive-sites': {get: {tags: ['Sitios sensibles'], summary: 'Lista los sitios sensibles de una ciudad', parameters: [{'$ref': '#/components/parameters/Id'}], responses: {'200': {description: 'Sitios sensibles de la ciudad'}, '404': {description: 'Ciudad no encontrada'}}}},
    '/api/v1/sensitive-sites/{id}': {put: {tags: ['Sitios sensibles'], summary: 'Actualiza un sitio sensible', parameters: [{'$ref': '#/components/parameters/Id'}], requestBody: {required: true, content: {'application/json': {schema: {$ref: '#/components/schemas/SensitiveSiteInput'}}}}, responses: {'200': {description: 'Actualizado'}}}, delete: {tags: ['Sitios sensibles'], summary: 'Elimina un sitio sensible', parameters: [{'$ref': '#/components/parameters/Id'}], responses: {'200': {description: 'Eliminado'}}}},
    '/api/v1/cities/{id}': {get: {tags: ['Ciudades'], summary: 'Obtiene una ciudad', parameters: [{'$ref': '#/components/parameters/Id'}], responses: {'200': {description: 'Ciudad'}, '404': {description: 'No encontrada'}}}, put: {tags: ['Ciudades'], summary: 'Actualiza una ciudad', parameters: [{'$ref': '#/components/parameters/Id'}], requestBody: {required: true, content: {'application/json': {schema: {$ref: '#/components/schemas/CityInput'}}}}, responses: {'200': {description: 'Actualizada'}}}, delete: {tags: ['Ciudades'], summary: 'Elimina una ciudad', parameters: [{'$ref': '#/components/parameters/Id'}], responses: {'200': {description: 'Eliminada'}}}}
  },
  components: {parameters: {Id: {name: 'id', in: 'path', required: true, schema: {type: 'integer', minimum: 1}}}, schemas: {CityInput: {type: 'object', required: ['name', 'latitude', 'longitude'], properties: {name: {type: 'string'}, country: {type: 'string'}, latitude: {type: 'number'}, longitude: {type: 'number'}, population: {type: 'integer', nullable: true}}}, SensitiveSiteInput: {type: 'object', required: ['city_id', 'name'], properties: {city_id: {type: 'integer'}, name: {type: 'string'}, type: {type: 'string'}}}, CityBulkInput: {oneOf: [{type: 'array', maxItems: 10000, items: {$ref: '#/components/schemas/CityInput'}}, {type: 'object', required: ['items'], properties: {items: {type: 'array', maxItems: 10000, items: {$ref: '#/components/schemas/CityInput'}}}}]}, SensitiveSiteBulkInput: {oneOf: [{type: 'array', maxItems: 10000, items: {$ref: '#/components/schemas/SensitiveSiteInput'}}, {type: 'object', required: ['items'], properties: {items: {type: 'array', maxItems: 10000, items: {$ref: '#/components/schemas/SensitiveSiteInput'}}}}]}}}
};
const html = `<!doctype html><html><head><title>MS2 Swagger UI</title><link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5.11.10/swagger-ui.css"></head><body><div id="swagger-ui"></div><script src="https://unpkg.com/swagger-ui-dist@5.11.10/swagger-ui-bundle.js"></script><script>SwaggerUIBundle({url:'openapi.json',dom_id:'#swagger-ui',deepLinking:true,presets:[SwaggerUIBundle.presets.apis,SwaggerUIBundle.SwaggerUIStandalonePreset]})</script></body></html>`;
module.exports = { spec, html };
